# Generated by Django 6.0.2 on 2026-03-07 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_alter_articles_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='release',
            field=models.DateField(blank=True, null=True),
        ),
    ]
